project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - chapters/00-OrientationProject/00-project.qmd
    - chapters/01-SettingUp/setting-up.qmd
    - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
    - chapters/03-RBasics/r-walkthrough.qmd
    - chapters/04-StatBasics/stat-basics.qmd
    - chapters/05-WorkingWithData/pythonAndR.qmd
    - chapters/05-WorkingWithData/r_penguins.qmd
    - chapters/05-WorkingWithData/pandas_penguins.qmd


website:
  title: "Fundamentals of Machine Learning"
  sidebar:
    contents:
      - section: "Contents"
        contents:
        - chapters/00-OrientationProject/00-project.qmd
        - chapters/01-SettingUp/setting-up.qmd  
        - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
        - chapters/03-RBasics/r-walkthrough.qmd
        - chapters/04-StatBasics/stat-basics.qmd  
        - chapters/05-WorkingWithData/pythonAndR.qmd
  

  
format:
  html:
    theme: cosmo

