project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - chapters/00-OrientationProject/orientation-project.qmd
    - chapters/01-SettingUp/setting-up.qmd
    - chapters/01-SettingUp/Cluster.md
    - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
    - chapters/03-RBasics/r-walkthrough.qmd
    - chapters/04-StatBasics/stat-basics.qmd
    - chapters/05-WorkingWithData/*.qmd
    - chapters/06-LinearAlgebra/linear_algebra.qmd  
    - chapters/06-LinearAlgebra/linear_algebra_python.qmd
    - chapters/06-LinearAlgebra/linear_algebra_r.qmd
    - chapters/07-Calculus/*.qmd
    - chapters/08-Summarizing/*.qmd
    - chapters/99-Resources/Cheatsheets.qmd
    - chapters/999-Problems/*.qmd

website:
  title: "Fundamentals of Machine Learning"
  sidebar:
    contents:
      - section: "Contents"
        contents:
        - chapters/00-OrientationProject/orientation-project.qmd
        - chapters/01-SettingUp/setting-up.qmd  
        - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
        - chapters/03-RBasics/r-walkthrough.qmd
        - chapters/04-StatBasics/stat-basics.qmd  
        - chapters/05-WorkingWithData/pythonAndR.qmd
        - chapters/06-LinearAlgebra/linear_algebra.qmd
        - chapters/07-Calculus/calculus.qmd
        - chapters/08-Summarizing/grouping_pandas.qmd
        - chapters/08-Summarizing/groupingR.qmd
      - section: "Problems"
        contents:
        - chapters/999-Problems/HW1.qmd
        - chapters/999-Problems/Distributions.qmd
        - chapters/999-Problems/HW2.qmd
        - chapters/999-Problems/HW2-clean_up_function.qmd
        - chapters/999-Problems/HW2-Iteration.qmd
        - chapters/999-Problems/HW2-Poisson.qmd
      - section: "Resources"
        contents:
        - chapters/99-Resources/Cheatsheets.qmd
	    - chapters/99-Resources/regexps.qmd

format:
  html:
    theme: lumen
    code-block-bg: true

