project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - chapters/01-SettingUp/setting-up.qmd
    - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
    - chapters/03-RBasics/r-walkthrough.qmd
    - chapters/04-StatBasics/stat-basics.qmd

website:
  title: "Fundamentals of Machine Learning"
  sidebar:
    style: "floating"
    contents:
      - section: "Contents"
        contents:
        - chapters/01-SettingUp/setting-up.qmd  
        - chapters/02-JupyterBasics/jupyter-walkthrough.qmd
        - chapters/03-RBasics/r-walkthrough.qmd
        - chapters/04-StatBasics/stat-basics.qmd  
  

  
format:
  html:
    theme: cosmo

