```{r echo=FALSE}
library(tidyverse)
library(palmerpenguins)
library(gridExtra)
```

```{r}
adelie <- penguins |>
    filter(`species` == "Adelie") |>
    drop_na()
```

## Histogram and ECDF

```{r}
hist<-ggplot(data=adelie)+geom_histogram(aes(x=`bill_length_mm`,y=after_stat(density)),binwidth=.2,color='white',fill='blue',alpha=.5)+
labs(x="Bill Length (mm)",y="Density", title="Histogram")
ecdf <-ggplot(data=adelie)+stat_ecdf(aes(x=`bill_length_mm`),color='red')+labs(x="Bill Length (mm)",y="Cumulative Density", title="ECDF")

grid.arrange(hist, ecdf, ncol = 2)
```


## Bootstrap means histogram
```{r}
bootstrap_mean <- function(data) {
    sample <- data |> sample_frac(1,replace=TRUE)
    return(mean(pull(sample)))
    
}

samples<-replicate(1000,bootstrap_mean(adelie|>select("bill_length_mm")))
ggplot()+geom_histogram(aes(x=samples,y=after_stat(density)))+labs(title='Bootstrap Means')
```


## Bootstrap means ECDF
```{r}
ggplot() + stat_ecdf(aes(x=samples))+labs(title="ECDF for bootstrap means",x="Sample Mean", y="Quantile")
```


## QQ plot

```{r}
ggplot(data=adelie)+stat_qq(aes(sample=`bill_length_mm`))+
    labs(title="QQ plot for Bill Length (mm)")
```

```{r}
show <- function(data, column) {
    hist<-ggplot(data=data)+geom_histogram(aes(x={{column}},y=after_stat(density)),binwidth=.2,color='white',fill='blue',alpha=.5)
    ecdf <-ggplot(data=data)+stat_ecdf(aes(x={{column}}),color='red')
    return(list(hist,ecdf))
}
grid.arrange(grobs=show(adelie,bill_length_mm),ncol=1)
```