---
title: "Uncertainty Quantification"
subtitle: "Fundamentals of Data Science"
author: "Jeremy Teitelbaum"
format: revealjs
title-block-style: plain
---

# Quantification of Uncertainty

## Pattern and Randomness

Randomness is an intrinsic aspect of our knowledge of the world.

We experience the world as a mixture of pattern and variation.

**Example:** The weather in the Spring is warmer than the weather in the winter but the weather on any given day is unpredictable

## Pattern is explained by scientific/mathematical models

- Newton's Laws and Theory of Gravity predict solar eclipses, motion of the planets, behavior of projectiles

- Mendel's laws and the central dogma of biology explains how DNA
controls characteristics of offspring in reproduction of organisms, 

- Mathematical epidemiology can predict spread of diseases in populations

- Behavior of options pricing governed by the Black-Scholes equation

## Statistical models

Statistics attempts to blend mathematical models with an understanding of randomness.

Make predictions with a known, or quantified, amount of uncertainty.

## Types of Uncertainty

But our ability to quantify uncertainty is limited in many ways:

- model uncertainty
- measurement uncertainty
- algorithmic uncertainty

## Model Uncertainty

Example: Coin flipping

- We believe the chance  of a head is 1/2
- Our model says coin gives either heads or tails with equal chance

## Model Uncertainty

We ignore:

- weird edge cases, 
- how the "flipping" is done,
- slight variation in weight of head/tails that might bias the coin
- different people doing experiment might get different results
- we might misrecord a H/T or miss a flip or read our data incorrectly

## Parameter Uncertainty

Motion of the planets depends on:

- the gravitational constant
- various masses

deduced from measurements --  all of which have inherent errors. 

## Algorithmic Uncertainty

Computations done numerically on a computer are subject to roundoff error

Algorithms for solving things like differential equations or computing integrals
are inherently approximations


