---
title: "Setting up a Project"
subtitle: "Fundamentals of Data Science"
author: "Jeremy Teitelbaum"
format: revealjs
title-block-style: plain
---

# Key Software Tools

## Anaconda Install for Python

- Download from 
[https://www.anaconda.com](https://www.anaconda.com)

Anaconda includes:

- python
- jupyter: notebook working environment
- python libraries: ML, visualization, I/O and others
- conda package manager: for dealing with multiple versions of libraries
- anaconda navigator: a GUI gateway to anaconda tools
- lots of other stuff

## Verify Anaconda

- Verify JupyterLab

From a command line
```bash
$ jupyter lab 
```
or use anaconda navigator to launch jupyterlab.

- Verify python version

From a command line
```bash
$ python --version
```
or inside a jupyter notebook cell:
```python
import sys
print(sys.version)
```

## R and Rstudio Install for R

- R is an open source language for statistical computations.
- Rstudio is a working environment for the R language.
- R and Rstudio need to be installed separately.

- R is available at [https://cran.r-project.org](https://cran.r-project.org)
- Rstudio is available at [https://posit.co/download/rstudio-desktop](https://posit.co/download/rstudio-desktop)

## Verify R and Rstudio

For R, From a command line:
```bash
$ R 
```

For Rstudio, use the icon/shortcut or from a command line:
```bash
$ rstudio 
```

## Setting up a Project

- Create a project directory
- Subdirectories
    - data for data files
    - docs for notes and documentation
    - others?

Use the finder or the command line


