---
title: "Jupyter Lab Project Walkthrough"
subtitle: "Fundamentals of Data Science"
author: "Jeremy Teitelbaum"
format: revealjs
title-block-style: plain
---

# Jupyter Lab Project Walkthrough

1. Use the 'text editor' feature in Jupyter Lab to create your README.md file.
2. **RENAME YOUR NOTEBOOK FILE IMMEDIATELY** to something relevant
3. CTRL-ENTER executes a cell.
4. See [this sample code](downloads/02-example.tgz)
    

## Markdown cells

In a markdown cell:

- Headings are \#, \#\#, etc.
- Bold is marked \*\*make me bold\*\* like **this**.
- Italics are marked \*make me italic\* like *this*.
- Math can be typeset with \LaTeX if you know it:  $$f(x)=e^{-x}\cos(x)$$
- Bulleted lists are marked with \-.

## Code Cells

```python
# code cells
## Code cells contain python code that gets executed.  
# indicates a comment that is ignored.
print("Hello World!")
```

    Hello World!

## Ingredients

1. The print statement
2. Basic datatypes:
    - numbers (integers and floats)
    - strings 
    - lists
    - True, False, and None
3. Variables, variable names, and assignment
    - **caution:** order of cell execution is what matters
4. Formatted print with variables

## Ingredients continued 

5. Arithmetic operations
6. Logical operations
7. Operations on strings and lists
8. Slicing
9. Libraries




