---
title: "Key Ideas from Statistics and Probability"
subtitle: "Fundamentals of Data Science"
author: "Jeremy Teitelbaum"
format: revealjs
title-block-style: plain
---

# Quantification of Uncertainty

## Pattern and Randomness

Randomness is an intrinsic aspect of our knowledge of the world.

We experience the world as a mixture of pattern and variation.

**Example:** The weather in the Spring is warmer than the weather in the winter but the weather on any given day is unpredictable

## Pattern is explained by scientific/mathematical models

- Newton's Laws and Theory of Gravity predict solar eclipses, motion of the planets, behavior of projectiles

- Mendel's laws and the central dogma of biology explains how DNA
controls characteristics of offspring in reproduction of organisms, 

- Mathematical epidemiology can predict spread of diseases in populations

- Behavior of options pricing governed by the Black-Scholes equation

## Statistical models

Statistics attempts to blend mathematical models with an understanding of randomness.

Make predictions with a known, or quantified, amount of uncertainty.

## Types of Uncertainty

But our ability to quantify uncertainty is limited in many ways:

-- model uncertainty
-- measurement uncertainty

Example: coin flipping
we believe Prob of a head is 1/2
design experiments to find evidence or not
model says coin gives either heads or tails with equal chance, but this ignores weird edge
cases, how the "flipping" is done, slight variation in weight of head/tails that might bias the coin
different people doing experiment might get different results
we might misrecord a H/T or miss a flip or read our data incorrectly


-- parameter uncertainty

motion of the planets depends on the gravitational constant, various masses, all of which have
some uncertainty built in

-- algorithmic uncertainty

computations done numerically on a computer are subject to roundoff error, which can be a source
of uncertainty.





## Populations and Samples

